// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Back.Models;

public partial class AsientosXreproduccione
{
    public int IdAsientoXreproduccion { get; set; }

    public bool Libre { get; set; }

    public int IdAsiento { get; set; }

    public int IdReproduccion { get; set; }

    public virtual Asiento IdAsientoNavigation { get; set; }

    public virtual Reproduccion IdReproduccionNavigation { get; set; }

    public AsientosXreproduccione(int idAsiento, int idReproduccion, bool libre)
    {
        this.IdAsiento = idAsiento;
        this.IdReproduccion = idReproduccion;
        this .Libre = libre;
    }
}