// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Back.Models;

public partial class Cartelera
{
    public int IdCartelera { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime FechaFin { get; set; }

    public virtual ICollection<PeliculasXcartelera> PeliculasXcarteleras { get; set; } = new List<PeliculasXcartelera>();
}