// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Back.Models;

public partial class Factura
{
    public int IdFactura { get; set; }

    public DateTime Fecha { get; set; }

    public int IdCliente { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public Factura(DateTime fecha, int idCliente)
    {
        this.Fecha = fecha;
        this.IdCliente = idCliente;
    }
}