// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Back.Models;

public partial class Fila
{
    public int IdFila { get; set; }

    public string Letra { get; set; }

    public int NumeroSala { get; set; }

    public virtual ICollection<Asiento> Asientos { get; set; } = new List<Asiento>();

    public virtual Sala NumeroSalaNavigation { get; set; }
}