// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Back.Models;

public partial class Idioma
{
    public int IdIdioma { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<PeliculasXidioma> PeliculasXidiomas { get; set; } = new List<PeliculasXidioma>();

    public virtual ICollection<Reproduccion> Reproducciones { get; set; } = new List<Reproduccion>();
}