// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Back.Models;

public partial class PeliculasXcartelera
{
    public int IdPeliculaXcartelera { get; set; }

    public int IdPelicula { get; set; }

    public int IdCartelera { get; set; }

    public virtual Cartelera IdCarteleraNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }

    public PeliculasXcartelera(int idpelicula, int idcartelera)
    {
        this.IdPelicula=idpelicula;
        this.IdCartelera=idcartelera;
    }
}