// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Back.Models;

public partial class Pelicula
{
    public int IdPelicula { get; set; }

    public string UrlPortada { get; set; }

    public string Nombre { get; set; }

    public DateOnly FechaEstreno { get; set; }

    public int DuracionMinutos { get; set; }

    public string Sinopsis { get; set; }

    public int IdGenero { get; set; }

    public bool? EstaActiva { get; set; }

    public virtual Genero IdGeneroNavigation { get; set; }

    public virtual ICollection<PeliculasXcartelera> PeliculasXcarteleras { get; set; } = new List<PeliculasXcartelera>();

    public virtual ICollection<PeliculasXidioma> PeliculasXidiomas { get; set; } = new List<PeliculasXidioma>();

    public virtual ICollection<Reproduccion> Reproducciones { get; set; } = new List<Reproduccion>();
}