// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Back.Models;

public partial class Sala
{
    public int NumeroSala { get; set; }

    public int IdTipoSala { get; set; }

    public virtual ICollection<Fila> Filas { get; set; } = new List<Fila>();

    public virtual TiposSala IdTipoSalaNavigation { get; set; }

    public virtual ICollection<Reproduccion> Reproducciones { get; set; } = new List<Reproduccion>();

    public virtual ICollection<SalasXempleado> SalasXempleados { get; set; } = new List<SalasXempleado>();
}