// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Back.Models;

public partial class Asiento
{
    public int IdAsiento { get; set; }

    public int NumeroAsiento { get; set; }

    public int IdFila { get; set; }

    public virtual ICollection<AsientosXreproduccione> AsientosXreproducciones { get; set; } = new List<AsientosXreproduccione>();

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Fila IdFilaNavigation { get; set; }
}